apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://master1
  name: local-server
contexts:
- context:
    cluster: local-server
    user: kubeletuser
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: kubeletuser
  user:
    password: PFK15d8JoTczqb3T
    username: admin
